# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    monitoramento   subscriber      all                     scram-sha-256
host    monitoramento   readonly        all                     scram-sha-256